"""
generator.py — Artifact generation logic for Satoshium certification artifacts.

All artifacts are derived from the canonical Certification Package JSON.
"""
import html as _html
import json
from pathlib import Path
from typing import Any, Dict, List

from .models import today_iso, now_iso


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _safe(val: Any, fallback: str = "N/A") -> str:
    """Return a string representation of val, or fallback if None/empty."""
    if val is None or str(val).strip() == "":
        return fallback
    return str(val)


def _h(val: Any, fallback: str = "N/A") -> str:
    """HTML-safe string — passes through _safe then HTML-escapes special chars."""
    return _html.escape(_safe(val, fallback))


def _evidence_table_md(refs: List[Dict]) -> str:
    if not refs:
        return "_No evidence items listed._\n"
    rows = ["| # | ID | Title | Type | Location |",
            "|---|---|---|---|---|"]
    for i, r in enumerate(refs, 1):
        rows.append(
            f"| {i} | {_safe(r.get('evidence_id'))} | {_safe(r.get('title'))} "
            f"| {_safe(r.get('type'))} | {_safe(r.get('location'))} |"
        )
    return "\n".join(rows) + "\n"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  Generated: {path.name}")


# ---------------------------------------------------------------------------
# Individual artifact generators
# ---------------------------------------------------------------------------

def gen_certification_package_md(pkg: Dict, out_dir: Path) -> None:
    cert_id     = _safe(pkg.get("certification_id"))
    subject     = pkg.get("subject", {})
    certifier   = pkg.get("certifier", {})
    standard    = pkg.get("standard", {})
    methodology = pkg.get("methodology", {})
    scope       = pkg.get("scope", {})
    outcome     = pkg.get("outcome", {})
    metadata    = pkg.get("metadata", {})
    refs        = pkg.get("evidence_references", [])

    inclusions = "\n".join(f"- {i}" for i in scope.get("inclusions", [])) or "_(none listed)_"
    exclusions = "\n".join(f"- {e}" for e in scope.get("exclusions", [])) or "_(none listed)_"
    conditions = "\n".join(f"- {c}" for c in outcome.get("conditions", [])) or "_(none listed)_"

    content = f"""# Certification Package — {cert_id}

**Status:** {_safe(pkg.get('status'))}  
**Issued Date:** {_safe(pkg.get('issued_date'))}  
**Effective Date:** {_safe(pkg.get('effective_date'))}  
**Expiry Date:** {_safe(pkg.get('expiry_date'))}  
**Schema Version:** {_safe(pkg.get('schema_version'))}

---

## Subject

| Field | Value |
|---|---|
| ID | {_safe(subject.get('id'))} |
| Name | {_safe(subject.get('name'))} |
| Type | {_safe(subject.get('type'))} |
| Version | {_safe(subject.get('version'))} |
| Repository | {_safe(subject.get('repository'))} |

**Description:** {_safe(subject.get('description'))}

---

## Certifier

| Field | Value |
|---|---|
| ID | {_safe(certifier.get('id'))} |
| Name | {_safe(certifier.get('name'))} |
| Role | {_safe(certifier.get('role'))} |
| Contact | {_safe(certifier.get('contact'))} |

---

## Standard

| Field | Value |
|---|---|
| ID | {_safe(standard.get('id'))} |
| Name | {_safe(standard.get('name'))} |
| Version | {_safe(standard.get('version'))} |
| Reference | {_safe(standard.get('reference_url'))} |

---

## Methodology

| Field | Value |
|---|---|
| ID | {_safe(methodology.get('id'))} |
| Name | {_safe(methodology.get('name'))} |
| Version | {_safe(methodology.get('version'))} |

**Description:** {_safe(methodology.get('description'))}

---

## Scope

**Summary:** {_safe(scope.get('summary'))}

**Inclusions:**
{inclusions}

**Exclusions:**
{exclusions}

---

## Outcome

**Status:** {_safe(outcome.get('status'))}  
**Determination Date:** {_safe(outcome.get('determination_date'))}  
**Summary:** {_safe(outcome.get('summary'))}

**Conditions:**
{conditions}

---

## Evidence References

{_evidence_table_md(refs)}

---

## Notes

{_safe(pkg.get('notes'))}

---

## Metadata

| Field | Value |
|---|---|
| Created By | {_safe(metadata.get('created_by'))} |
| Created At | {_safe(metadata.get('created_at'))} |
| Last Modified By | {_safe(metadata.get('last_modified_by'))} |
| Last Modified At | {_safe(metadata.get('last_modified_at'))} |

_Generated by satoshium-certifier-ops-toolkit on {today_iso()}_
"""
    _write(out_dir / "certification_package.md", content)


def gen_scpr_md(pkg: Dict, out_dir: Path) -> None:
    cert_id = _safe(pkg.get("certification_id"))
    subject = pkg.get("subject", {})
    outcome = pkg.get("outcome", {})
    refs    = pkg.get("evidence_references", [])

    content = f"""# SCPR — Satoshium Certification Progress Report

**Certification ID:** {cert_id}  
**Report Date:** {today_iso()}  
**Subject:** {_safe(subject.get('name'))} ({_safe(subject.get('id'))})  
**Current Status:** {_safe(pkg.get('status'))}

---

## Progress Summary

{_safe(outcome.get('summary'))}

---

## Evidence Items ({len(refs)} total)

{_evidence_table_md(refs)}

---

## Outstanding Items

_List any outstanding items, open questions, or pending evidence here._

---

_Generated by satoshium-certifier-ops-toolkit on {today_iso()}_
"""
    _write(out_dir / "scpr.md", content)


def gen_scr_md(pkg: Dict, out_dir: Path) -> None:
    cert_id   = _safe(pkg.get("certification_id"))
    subject   = pkg.get("subject", {})
    certifier = pkg.get("certifier", {})
    standard  = pkg.get("standard", {})
    outcome   = pkg.get("outcome", {})
    refs      = pkg.get("evidence_references", [])

    content = f"""# SCR — Satoshium Certification Record

**Certification ID:** {cert_id}  
**Issued Date:** {_safe(pkg.get('issued_date'))}  
**Status:** {_safe(pkg.get('status'))}

---

## Subject

**{_safe(subject.get('name'))}** (`{_safe(subject.get('id'))}`)  
Type: {_safe(subject.get('type'))}  
Version: {_safe(subject.get('version'))}

> {_safe(subject.get('description'))}

---

## Certifier

**{_safe(certifier.get('name'))}** (`{_safe(certifier.get('id'))}`)  
Role: {_safe(certifier.get('role'))}

---

## Standard

**{_safe(standard.get('name'))}** v{_safe(standard.get('version'))}  
ID: `{_safe(standard.get('id'))}`

---

## Outcome

| Field | Value |
|---|---|
| Status | {_safe(outcome.get('status'))} |
| Determination Date | {_safe(outcome.get('determination_date'))} |

**Summary:**  
{_safe(outcome.get('summary'))}

---

## Evidence Summary

{_evidence_table_md(refs)}

---

_Generated by satoshium-certifier-ops-toolkit on {today_iso()}_
"""
    _write(out_dir / "scr.md", content)


def gen_scrd_json(pkg: Dict, out_dir: Path) -> None:
    cert_id   = _safe(pkg.get("certification_id"))
    subject   = pkg.get("subject", {})
    certifier = pkg.get("certifier", {})
    standard  = pkg.get("standard", {})
    outcome   = pkg.get("outcome", {})
    refs      = pkg.get("evidence_references", [])
    related   = pkg.get("related_artifacts", {})

    scrd = {
        "scrd_id":          _safe(related.get("scrd_id"), f"SCRD-{cert_id}"),
        "certification_id": cert_id,
        "document_title":   f"Satoshium Certification Record Document \u2014 {cert_id}",
        "generated_date":   today_iso(),
        "version":          "1.0.0",
        "subject": {
            "id":          _safe(subject.get("id")),
            "name":        _safe(subject.get("name")),
            "type":        _safe(subject.get("type")),
            "version":     _safe(subject.get("version")),
            "description": _safe(subject.get("description")),
        },
        "certifier": {
            "id":   _safe(certifier.get("id")),
            "name": _safe(certifier.get("name")),
            "role": _safe(certifier.get("role")),
        },
        "standard": {
            "id":      _safe(standard.get("id")),
            "name":    _safe(standard.get("name")),
            "version": _safe(standard.get("version")),
        },
        "outcome": {
            "status":             _safe(outcome.get("status")),
            "summary":            _safe(outcome.get("summary")),
            "determination_date": _safe(outcome.get("determination_date")),
        },
        "evidence_count": len(refs),
        "metadata": {
            "generated_by": "satoshium-certifier-ops-toolkit",
            "generated_at": now_iso(),
        },
    }
    _write(out_dir / "scrd.json", json.dumps(scrd, indent=2))


def gen_scrd_html(pkg: Dict, out_dir: Path) -> None:
    """Generate the SCRD HTML artifact.

    All user-supplied field values are passed through _h() (html.escape) before
    being inserted into the document to prevent character corruption or injection
    if field data happens to contain HTML special characters.
    """
    cert_id   = _h(pkg.get("certification_id"))
    subject   = pkg.get("subject", {})
    certifier = pkg.get("certifier", {})
    standard  = pkg.get("standard", {})
    outcome   = pkg.get("outcome", {})
    refs      = pkg.get("evidence_references", [])

    # Status values are validated against an enum but escape anyway for safety
    status_raw     = _safe(pkg.get("status"))
    status_display = _h(pkg.get("status"))
    outcome_status_raw     = _safe(outcome.get("status"))
    outcome_status_display = _h(outcome.get("status"))

    ev_rows = ""
    for i, r in enumerate(refs, 1):
        ev_rows += (
            f"<tr><td>{i}</td>"
            f"<td>{_h(r.get('evidence_id'))}</td>"
            f"<td>{_h(r.get('title'))}</td>"
            f"<td>{_h(r.get('type'))}</td>"
            f"<td>{_h(r.get('location'))}</td></tr>\n"
        )
    if not ev_rows:
        ev_rows = "<tr><td colspan='5'><em>No evidence items listed.</em></td></tr>"

    html_doc = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SCRD &mdash; {cert_id}</title>
  <style>
    body {{ font-family: Georgia, serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #222; }}
    h1 {{ border-bottom: 2px solid #333; padding-bottom: 10px; }}
    h2 {{ margin-top: 36px; border-bottom: 1px solid #ccc; }}
    table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
    th {{ background: #f0f0f0; text-align: left; padding: 8px 12px; border: 1px solid #ccc; }}
    td {{ padding: 7px 12px; border: 1px solid #ddd; vertical-align: top; }}
    .badge {{ display: inline-block; padding: 3px 10px; border-radius: 4px;
              font-size: 0.85em; font-family: monospace; font-weight: bold; }}
    .status-CERTIFIED {{ background: #d4edda; color: #155724; }}
    .status-PENDING   {{ background: #fff3cd; color: #856404; }}
    .status-REJECTED  {{ background: #f8d7da; color: #721c24; }}
    .status-SUSPENDED {{ background: #d6d8db; color: #383d41; }}
    .status-WITHDRAWN {{ background: #e2e3e5; color: #383d41; }}
    footer {{ margin-top: 60px; font-size: 0.8em; color: #777; border-top: 1px solid #eee; padding-top: 10px; }}
  </style>
</head>
<body>
  <h1>Satoshium Certification Record Document</h1>

  <table>
    <tr><th>Certification ID</th><td><strong>{cert_id}</strong></td></tr>
    <tr><th>Status</th><td><span class="badge status-{status_raw}">{status_display}</span></td></tr>
    <tr><th>Issued Date</th><td>{_h(pkg.get('issued_date'))}</td></tr>
    <tr><th>Effective Date</th><td>{_h(pkg.get('effective_date'))}</td></tr>
    <tr><th>Expiry Date</th><td>{_h(pkg.get('expiry_date'))}</td></tr>
    <tr><th>Schema Version</th><td>{_h(pkg.get('schema_version'))}</td></tr>
  </table>

  <h2>Subject</h2>
  <table>
    <tr><th>ID</th><td>{_h(subject.get('id'))}</td></tr>
    <tr><th>Name</th><td>{_h(subject.get('name'))}</td></tr>
    <tr><th>Type</th><td>{_h(subject.get('type'))}</td></tr>
    <tr><th>Version</th><td>{_h(subject.get('version'))}</td></tr>
    <tr><th>Description</th><td>{_h(subject.get('description'))}</td></tr>
    <tr><th>Repository</th><td>{_h(subject.get('repository'))}</td></tr>
  </table>

  <h2>Certifier</h2>
  <table>
    <tr><th>ID</th><td>{_h(certifier.get('id'))}</td></tr>
    <tr><th>Name</th><td>{_h(certifier.get('name'))}</td></tr>
    <tr><th>Role</th><td>{_h(certifier.get('role'))}</td></tr>
    <tr><th>Contact</th><td>{_h(certifier.get('contact'))}</td></tr>
  </table>

  <h2>Standard</h2>
  <table>
    <tr><th>ID</th><td>{_h(standard.get('id'))}</td></tr>
    <tr><th>Name</th><td>{_h(standard.get('name'))}</td></tr>
    <tr><th>Version</th><td>{_h(standard.get('version'))}</td></tr>
    <tr><th>Reference</th><td>{_h(standard.get('reference_url'))}</td></tr>
  </table>

  <h2>Outcome</h2>
  <table>
    <tr><th>Status</th><td><span class="badge status-{outcome_status_raw}">{outcome_status_display}</span></td></tr>
    <tr><th>Determination Date</th><td>{_h(outcome.get('determination_date'))}</td></tr>
    <tr><th>Summary</th><td>{_h(outcome.get('summary'))}</td></tr>
  </table>

  <h2>Evidence References ({len(refs)} items)</h2>
  <table>
    <thead>
      <tr><th>#</th><th>ID</th><th>Title</th><th>Type</th><th>Location</th></tr>
    </thead>
    <tbody>
      {ev_rows}
    </tbody>
  </table>

  <footer>
    Generated by <strong>satoshium-certifier-ops-toolkit</strong> on {_h(today_iso())}.
  </footer>
</body>
</html>
"""
    _write(out_dir / "scrd.html", html_doc)


def gen_evidence_inventory_json(pkg: Dict, out_dir: Path) -> None:
    cert_id = _safe(pkg.get("certification_id"))
    refs    = pkg.get("evidence_references", [])

    items = []
    for r in refs:
        items.append({
            "evidence_id":    _safe(r.get("evidence_id")),
            "title":          _safe(r.get("title")),
            "type":           _safe(r.get("type")),
            "description":    _safe(r.get("description", "")),
            "location":       _safe(r.get("location")),
            "format":         _safe(r.get("format", "")),
            "hash":           _safe(r.get("hash", "")),
            "collected_date": _safe(r.get("collected_date", "")),
            "collected_by":   _safe(r.get("collected_by", "")),
            "status":         "COLLECTED",
            "notes":          _safe(r.get("notes", "")),
        })

    inventory = {
        "certification_id": cert_id,
        "generated_date":   today_iso(),
        "total_items":      len(items),
        "items":            items,
    }
    _write(out_dir / "evidence_inventory.json", json.dumps(inventory, indent=2))


def gen_evidence_map_md(pkg: Dict, out_dir: Path) -> None:
    cert_id = _safe(pkg.get("certification_id"))
    refs    = pkg.get("evidence_references", [])

    lines = [
        f"# Evidence Map \u2014 {cert_id}",
        "",
        f"**Total evidence items:** {len(refs)}  ",
        f"**Generated:** {today_iso()}",
        "",
        "---",
        "",
    ]

    if refs:
        for i, r in enumerate(refs, 1):
            lines += [
                f"## {i}. {_safe(r.get('title'))}",
                "",
                "| Field | Value |",
                "|---|---|",
                f"| Evidence ID | `{_safe(r.get('evidence_id'))}` |",
                f"| Type | {_safe(r.get('type'))} |",
                f"| Location | {_safe(r.get('location'))} |",
                f"| Hash | `{_safe(r.get('hash', '(not provided)'))}` |",
                f"| Collected Date | {_safe(r.get('collected_date', '(not provided)'))} |",
                "",
            ]
    else:
        lines.append("_No evidence items listed in the Certification Package._")

    lines += [
        "---",
        "",
        f"_Generated by satoshium-certifier-ops-toolkit on {today_iso()}_",
    ]
    _write(out_dir / "evidence_map.md", "\n".join(lines))


def gen_sreg_stub(pkg: Dict, out_dir: Path) -> None:
    cert_id   = _safe(pkg.get("certification_id"))
    subject   = pkg.get("subject", {})
    certifier = pkg.get("certifier", {})
    standard  = pkg.get("standard", {})
    related   = pkg.get("related_artifacts", {})

    stub = {
        "_note":                    "SREG stub — populate PLACEHOLDER fields before Registry submission.",
        "sreg_id":                  _safe(related.get("sreg_id"), "SREG-ID-PLACEHOLDER"),
        "certification_id":         cert_id,
        "entry_type":               "REGISTRY-ENTRY-TYPE-PLACEHOLDER",
        "subject_id":               _safe(subject.get("id")),
        "subject_name":             _safe(subject.get("name")),
        "certifier_id":             _safe(certifier.get("id")),
        "standard_id":              _safe(standard.get("id")),
        "outcome_status":           _safe(pkg.get("status")),
        "issued_date":              _safe(pkg.get("issued_date")),
        "registry_submission_date": "YYYY-MM-DD",
        "registry_reference":       "REGISTRY-REFERENCE-PLACEHOLDER",
        "metadata": {
            "generated_by": "satoshium-certifier-ops-toolkit",
            "generated_at": now_iso(),
        },
    }
    _write(out_dir / "sreg_stub.json", json.dumps(stub, indent=2))


def gen_schr_stub(pkg: Dict, out_dir: Path) -> None:
    cert_id   = _safe(pkg.get("certification_id"))
    subject   = pkg.get("subject", {})
    certifier = pkg.get("certifier", {})
    related   = pkg.get("related_artifacts", {})

    stub = {
        "_note":               "SCHR stub — populate PLACEHOLDER fields before Chronicle submission.",
        "schr_id":             _safe(related.get("schr_id"), "SCHR-ID-PLACEHOLDER"),
        "certification_id":    cert_id,
        "chronicle_type":      "CHRONICLE-TYPE-PLACEHOLDER",
        "subject_id":          _safe(subject.get("id")),
        "certifier_id":        _safe(certifier.get("id")),
        "event_date":          _safe(pkg.get("issued_date")),
        "event_description":   "CHRONICLE-EVENT-DESCRIPTION-PLACEHOLDER",
        "preceding_record_id": "PRECEDING-SCHR-ID-PLACEHOLDER",
        "metadata": {
            "generated_by": "satoshium-certifier-ops-toolkit",
            "generated_at": now_iso(),
        },
    }
    _write(out_dir / "schr_stub.json", json.dumps(stub, indent=2))


def gen_anch_stub(pkg: Dict, out_dir: Path) -> None:
    cert_id   = _safe(pkg.get("certification_id"))
    certifier = pkg.get("certifier", {})
    related   = pkg.get("related_artifacts", {})

    stub = {
        "_note":                "ANCH stub — populate PLACEHOLDER fields before anchoring.",
        "anch_id":              _safe(related.get("anch_id"), "ANCH-ID-PLACEHOLDER"),
        "certification_id":     cert_id,
        "anchor_type":          "ANCHOR-TYPE-PLACEHOLDER",
        "anchor_target":        "ANCHOR-TARGET-PLACEHOLDER",
        "anchor_hash":          "ANCHOR-HASH-PLACEHOLDER",
        "anchor_timestamp":     "YYYY-MM-DDTHH:MM:SSZ",
        "anchor_reference_url": "ANCHOR-REFERENCE-URL-PLACEHOLDER",
        "certifier_id":         _safe(certifier.get("id")),
        "metadata": {
            "generated_by": "satoshium-certifier-ops-toolkit",
            "generated_at": now_iso(),
        },
    }
    _write(out_dir / "anch_stub.json", json.dumps(stub, indent=2))


def gen_satr_stub(pkg: Dict, out_dir: Path) -> None:
    cert_id   = _safe(pkg.get("certification_id"))
    subject   = pkg.get("subject", {})
    certifier = pkg.get("certifier", {})
    related   = pkg.get("related_artifacts", {})

    stub = {
        "_note":                 "SATR stub — populate PLACEHOLDER fields before Attestor submission.",
        "satr_id":               _safe(related.get("satr_id"), "SATR-ID-PLACEHOLDER"),
        "certification_id":      cert_id,
        "attestation_type":      "ATTESTATION-TYPE-PLACEHOLDER",
        "attestor_id":           "ATTESTOR-ID-PLACEHOLDER",
        "attestor_name":         "ATTESTOR-NAME-PLACEHOLDER",
        "subject_id":            _safe(subject.get("id")),
        "certifier_id":          _safe(certifier.get("id")),
        "attestation_date":      "YYYY-MM-DD",
        "attestation_statement": "ATTESTATION-STATEMENT-PLACEHOLDER",
        "attestation_signature": "ATTESTATION-SIGNATURE-PLACEHOLDER",
        "metadata": {
            "generated_by": "satoshium-certifier-ops-toolkit",
            "generated_at": now_iso(),
        },
    }
    _write(out_dir / "satr_stub.json", json.dumps(stub, indent=2))


def gen_release_checklist_md(pkg: Dict, out_dir: Path) -> None:
    cert_id = _safe(pkg.get("certification_id"))
    all_artifacts = [
        ("certification_package.json",  "Canonical certification object (JSON)"),
        ("certification_package.md",    "Human-readable certification summary (Markdown)"),
        ("scpr.md",                     "Satoshium Certification Progress Report (Markdown)"),
        ("scr.md",                      "Satoshium Certification Record (Markdown)"),
        ("scrd.html",                   "Satoshium Certification Record Document (HTML)"),
        ("scrd.json",                   "Satoshium Certification Record Document (JSON)"),
        ("evidence_inventory.json",     "Evidence Inventory (JSON)"),
        ("evidence_map.md",             "Evidence Map (Markdown)"),
        ("sreg_stub.json",              "SREG Registry Entry stub (JSON)"),
        ("schr_stub.json",              "SCHR Chronicle Record stub (JSON)"),
        ("anch_stub.json",              "ANCH Anchor Reference stub (JSON)"),
        ("satr_stub.json",              "SATR Attestation Record stub (JSON)"),
        ("release_checklist.md",        "This release checklist (Markdown)"),
    ]

    rows = "\n".join(
        f"- [ ] `{fname}` \u2014 {desc}"
        for fname, desc in all_artifacts
    )

    content = f"""# Release Checklist \u2014 {cert_id}

Generated: {today_iso()}

## Artifact Presence

Verify that each artifact file exists and all placeholder values have been replaced:

{rows}

---

## Validation Steps

- [ ] `python scripts/validate_certification.py output/{cert_id}` \u2014 passes with 0 errors
- [ ] `python scripts/check_release.py output/{cert_id}` \u2014 passes with 0 missing files and 0 placeholders

---

## Pre-Release Sign-off

- [ ] Certification Package JSON reviewed by certifier
- [ ] Outcome status confirmed (not PENDING)
- [ ] Evidence references verified complete
- [ ] SREG stub ready for Registry submission
- [ ] SCHR stub ready for Chronicle submission
- [ ] ANCH stub ready for anchoring
- [ ] SATR stub ready for Attestor submission

---

_Generated by satoshium-certifier-ops-toolkit on {today_iso()}_
"""
    _write(out_dir / "release_checklist.md", content)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def generate_all_artifacts(pkg: Dict, out_dir: Path) -> None:
    """Generate all derived artifacts from the canonical Certification Package JSON."""
    print(f"\nGenerating artifacts in: {out_dir}\n")
    gen_certification_package_md(pkg, out_dir)
    gen_scpr_md(pkg, out_dir)
    gen_scr_md(pkg, out_dir)
    gen_scrd_json(pkg, out_dir)
    gen_scrd_html(pkg, out_dir)
    gen_evidence_inventory_json(pkg, out_dir)
    gen_evidence_map_md(pkg, out_dir)
    gen_sreg_stub(pkg, out_dir)
    gen_schr_stub(pkg, out_dir)
    gen_anch_stub(pkg, out_dir)
    gen_satr_stub(pkg, out_dir)
    gen_release_checklist_md(pkg, out_dir)
    print(f"\nDone. 12 artifacts generated.\n")
